# Generated by Django 6.0.4 on 2026-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
