# Generated by Django 6.0.4 on 2026-04-11 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1930, message='Год рождения не может быть меньше 1930.'), django.core.validators.MaxValueValidator(2026, message='Год рождения не может быть больше текущего.')], verbose_name='Дата рождения'),
        ),
    ]
