# Generated by Django 6.0.4 on 2026-04-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Athlete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лиги (Хард, Лайт и т.д.)')),
                ('points_1', models.PositiveIntegerField(default=0, verbose_name='Очки за 1 место')),
                ('points_2', models.PositiveIntegerField(default=0, verbose_name='Очки за 2 место')),
                ('points_3', models.PositiveIntegerField(default=0, verbose_name='Очки за 3 место')),
                ('points_4', models.PositiveIntegerField(default=0, verbose_name='Очки за 4 место')),
                ('points_other', models.PositiveIntegerField(default=0, verbose_name='Очки остальным')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес проведения')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Турнир завершен (очки начислены)')),
                ('birth_year_from', models.PositiveIntegerField(blank=True, help_text='Например: 2011', null=True, verbose_name='Год рождения от')),
                ('birth_year_to', models.PositiveIntegerField(blank=True, help_text='Например: 2014', null=True, verbose_name='Год рождения до')),
                ('allowed_gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('MIX', 'Микст (М+Ж)'), ('ANY', 'Любой')], default='ANY', max_length=3, verbose_name='Допустимый пол участников')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговое место в турнире')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Turnir.league', verbose_name='Лига')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_p1', to='Athlete.athlete', verbose_name='Игрок 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_p2', to='Athlete.athlete', verbose_name='Игрок 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnir.tournament', verbose_name='Турнир')),
            ],
        ),
    ]
