# Generated by Django 6.0.4 on 2026-04-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_points_awarded',
            field=models.BooleanField(default=False, verbose_name='Очки уже начислены'),
        ),
    ]
