# Generated by Django 6.0.4 on 2026-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnir', '0002_team_is_points_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_points_awarded',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='allowed_gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('MIX', 'Микст (М+Ж)'), ('ANY', 'Любой')], default='ANY', max_length=3, verbose_name='Допустимый пол'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='birth_year_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения от'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='birth_year_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения до'),
        ),
    ]
