# Generated by Django 6.0.4 on 2026-04-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnir', '0003_remove_team_is_points_awarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=50, verbose_name='Стадия турнира')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Матч завершен')),
                ('court', models.PositiveIntegerField(blank=True, null=True, verbose_name='Корт')),
                ('team1_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счет команды 1')),
                ('team2_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счет команды 2')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_referee', to='Turnir.team', verbose_name='Судит')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='Turnir.team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='Turnir.team', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnir.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['is_finished', 'court'],
            },
        ),
    ]
